### ISSUE TITLE
mustache + unicode (east european chars) problem on Win10

### ISSUE THREAD

**Issue by majkaz** [CDSoft/pp#70]
I have a problem with the **mustache** part of pp with combination with UTF files, containing **combining characters in yaml values**. 

This is the result:
`InvalidYaml (Just (YamlParseException {yamlProblem = "control characters are not allowed", yamlContext` or simply a wrong interpretation of the characters for other chars.

I have tested the [example script](https://github.com/CDSoft/pp#mustache-templates) and it is working in my current setup. But as soon as I change the yaml file to include the Czech characters, it fails - either completely or just putting wrong output out.

Try this, notice the changes in `github` and `author`:
```yaml
name:                pp
version:             2.7.2
github:              "ČDSoft/pp"
license:             GPL-3
author:              "Chřistophe Delord"
maintainer:          "cdsoft.fr"
copyright:           "2015-2019 Christophe Delord"
```

The change in `github` causes the `InvalidYaml` message, the `author` one results in `ChYistophe Delord` in the output.
I have tried both UTF with and without BOM, as well as CP1250 encoding.
